ToDoList.PL/Controllers/ObjectController.cs
using BresentationLogicLayer.Interfaces;
using DataAccessLayer.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace _objectInterface.PL.Controllers
{
    public class ObjectController : Controller
    {
       
        
        private readonly IUnitOfWork _unitOfWork;

        public ObjectController(IUnitOfWork unitOfWork)
        {
            
            _unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> Index()
        {
            var GetAll = await _unitOfWork.objectInterface.GetAllTasksAsync();
            return View(GetAll);
        }
        public async Task<IActionResult> Create(Objects objects)

        {
            
            if (ModelState.IsValid)
            {
                await _unitOfWork.objectInterface.AddAsync(objects);
                await _unitOfWork.CompleteAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(objects);
        }
        public async Task<IActionResult> Upadte(int? Id)
        {   
            if (!Id.HasValue)
            {
                return BadRequest();
            }
            var GetById = await _unitOfWork.objectInterface.GetTaskByIdAsync(Id.Value);
            if (GetById is null)
            {
                return NotFound();
            }
            return View(GetById);
        }
        [HttpPost]
        public async Task<IActionResult> Upadte(Objects  objects)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _unitOfWork.objectInterface.Update(objects);
                    await _unitOfWork.CompleteAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }
            return View(objects);
        }

        public async Task<IActionResult> Delete(Objects objects)
        {
            if (objects is not null)
            {
                 _unitOfWork.objectInterface.Delete(objects);
               await _unitOfWork.CompleteAsync();

            }
            return RedirectToAction(nameof(Index));
        }
    }
}

ToDoList.PL/Controllers/RollesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using ToDoList.PL.ViewModels;

namespace ToDoList.PL.Controllers
{
    public class RollesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RollesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Index()
        {

            var users = await _roleManager.Roles.Select(
                   U => new RolesViewModel()
                   {
                       ID = U.Id,
                       Name = U.Name

                   }).ToListAsync();
            return View(users);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(RolesViewModel model)
        {
            if (ModelState.IsValid)
            {
                var Mapped = new IdentityRole()
                {
                    Id = model.ID,
                    Name = model.Name
                };
                await _roleManager.CreateAsync(Mapped);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
        public async Task<IActionResult> Details(string ID, string viewModel = "Details")
        {
            var user = await _roleManager.FindByIdAsync(ID);
            if (user is null)
            {
                return NotFound();
            }
            var mapped = new RolesViewModel()
            {
                Name = user.Name
               
            };
            return View(viewModel, mapped);
        }
        public async Task<IActionResult> Edit(string id)
        {
            return await Details(id, "Edit");
        }
        [HttpPost]
        public async Task<IActionResult> Edit(RolesViewModel model, string id)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _roleManager.FindByIdAsync(id);
                    user.Name = model.Name;
                    
                    return RedirectToAction(nameof(Index));

                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }
            return View(model);
        }
        public async Task<IActionResult> Delete(string id)
        {
            return await Details(id, "Delete");
        }
        [HttpPost]
        public async Task<IActionResult> DeleteConfirm(string id)
        {

            try
            {
                var user = await _roleManager.FindByIdAsync(id);
                await _roleManager.DeleteAsync(user);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

ToDoList.PL/Controllers/UserController.cs
using AutoMapper;
using DataAccessLayer.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;
using ToDoList.PL.ViewModels;

namespace ToDoList.PL.Controllers
{
    public class UserController : Controller
    {
        private readonly IMapper _mapper;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public UserController(IMapper mapper, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            _mapper = mapper;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public async Task<IActionResult> Index(string SearchValue)
        {
            if (string.IsNullOrEmpty(SearchValue))
            {
                var users = await _userManager.Users.Select(
                    U => new UserViewModel()
                    {
                        Id = U.Id,
                        Fname = U.Fname,
                        Lname = U.Lname,
                        Email = U.Email,
                        PhoneNumber = U.PhoneNumber,
                        Roles = _userManager.GetRolesAsync(U).Result

                    }).ToListAsync();
                return View(users);
            }
            else
            {
                var User = await _userManager.FindByEmailAsync(SearchValue);
                var Mapped = new UserViewModel()
                {
                    Id = User.Id,
                    Fname = User.Fname,
                    Lname = User.Lname,
                    PhoneNumber = User.PhoneNumber,
                    Roles = _userManager.GetRolesAsync(User).Result
                };

                return View(new List<UserViewModel>() { Mapped });
            }


        }
        public async Task<IActionResult> Details(string ID, string viewModel = "Details")
        {
            var user = await _userManager.FindByIdAsync(ID);
            if (user is null)
            {
                return NotFound();
            }
            var mapped = new UserViewModel()
            {
                Id = user.Id,
                Fname = user.Fname,
                Lname = user.Lname,
                Email = user.Email,
                PhoneNumber = user.PhoneNumber,
                Roles = _userManager.GetRolesAsync(user).Result
            };
            return View(viewModel, mapped);
        }
        public async Task<IActionResult> Edit(string id)
        {
            return await Details(id, "Edit");
        }
        [HttpPost]
        public async Task<IActionResult> Edit(UserViewModel model, string id)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _userManager.FindByIdAsync(id);
                    user.Fname = model.Fname;
                    user.Lname = model.Lname;
                    user.PhoneNumber = model.PhoneNumber;
                    await _userManager.UpdateAsync(user);
                    return RedirectToAction(nameof(Index));

                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }
            return View(model);
        }
        public async Task<IActionResult> Delete(string id)
        {
            return await Details(id, "Delete");
        }
        [HttpPost]
        public async Task<IActionResult> DeleteConfirm(string id)
        {
            
                try
                {
                    var user = await _userManager.FindByIdAsync(id);
                    await _userManager.DeleteAsync(user);
                    return RedirectToAction(nameof(Index));
                }
                catch(Exception ex)
                {
                    ModelState.AddModelError(string.Empty,ex.Message);
                    return RedirectToAction("Error","Home");
                }  
        }
    }
}

ToDoList.PL/Views/Shared/AuthLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>@ViewData["Title"]</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <link href="~/css/authstylesheet.css" rel="stylesheet" />
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		
		@RenderBody()
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	@await RenderSectionAsync("ValidationForRegister", required: false)
</body>
</html>

ToDoList.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoList.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="bg-light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand "  asp-area="" asp-controller="Home" asp-action="Index">ToDoList</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>                       
                         <li class="nav-item">      
                            <a class="nav-link text-light"  asp-controller="ToDoList" asp-action="Index">Tasks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="Object" asp-action="Index">Object</a>
                        </li>
                          <li class="nav-item ml-auto text-danger">
                            <a class="nav-link text-light" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item ml-auto text-danger">
                            <a class="nav-link text-light" asp-controller="Rolles" asp-action="Index">Roles</a>
                        </li>
                         <li class="nav-item ml-auto text-danger">
                            <a class="nav-link text-light" asp-controller="Account" asp-action="LogOut">Log Out</a>
                        </li>
                      
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted navbar-dark bg-dark">
        <div class="container text-light">
            &copy; 2023 - ToDoList - <a asp-area="" asp-controller="Home" class="text-light" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("Validation", required: false)
</body>
</html>